language: python
python:
  - "3.6"
  - "nightly"
install:
  - "pip install pytest"
  - "pip install pytest-cov"
  - "pip install -r requirements.txt"
script:
  - python -m pytest --cov=tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)